### ISSUE TITLE
With no Configuration parameter on a project TODO message is produced

### ISSUE THREAD

**Issue by banjaxxer** [IBM/cics-bundle-gradle#19]
Multi project build.  Configuration commented out
dependencies {
	cicsBundle project(path: ':testData4.war' /*, configuration: 'war'*/)
}

Build fails with message: > TODO Parse version from file name or pass in from cicsBundle config dependency

**Comment by tom-foyle** [comment]
Interesting one this. When no configuration is specified, it uses the default configuration. For all types of Java projects, the default configuration contains the project packaged as a simple jar. So in this example the dependency will resolve to testData4.jar rather than testData4.war. We detect the jar extension and treat it as an OSGi bundle. We attempt to read the OSGi manifest file, which doesn't exist, and get an error. I've improved the error message to be more clear and indicate that the bundle part is being processed as an OSGi bundle, which should be enough to tell the user that something is wrong with their configuration.
